### ISSUE TITLE
Build fails after update to 2.0.0

### ISSUE THREAD

**Issue by siiick** [pascaliske/ngx-sentry#38]
Just upgrade from 1.4.0 to 2.0.0 and build fails.
See the output below : 

`ERROR in node_modules/@pascaliske/ngx-sentry/lib/sentry.service.d.ts(1,32): error TS2305: Module '"/Users/nicolas.c/vestiaire/ngx-web/node_modules/@sentry/browser/dist/index"' has no exported member 'Event'.`

**Comment by pascaliske** [comment]
Hello @siiick,

Thank you for opening this issue!

Did you also upgrade `@sentry/browser` module to at least `^5.0.5`?
They renamed the `SentryEvent` type internally to `Event` and [I had to increase the peer dependency of `@sentry/browser` to `^5.0.5`](https://github.com/pascaliske/ngx-sentry/commit/79e898955018555071513f1f78c16ff1c59f44aa?w=1) to get their latest size improvements.

Hope this info helps! 🙂

**Comment by pascaliske** [comment]
Closed due to inactivity. Feel free to open it again if the problem still exists for you.
